export const FORGOT_PASSWORD_EMAIL_CHANGED = 'FORGOT_PASSWORD_EMAIL_CHANGED';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_CLEANUP = 'FORGOT_PASSWORD_CLEANUP';

