export const CHANGE_PASSWORD_PASSWORD_CHANGED = 'CHANGE_PASSWORD_PASSWORD_CHANGED';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_CLEANUP = 'CHANGE_PASSWORD_CLEANUP';
