export const SIGNIN_EMAIL_CHANGED = 'SIGNIN_EMAIL_CHANGED';
export const SIGNIN_PASSWORD_CHANGED = 'SIGNIN_PASSWORD_CHANGED';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAIL = 'SIGNIN_FAIL';
export const SIGNIN = 'SIGNIN';
export const SIGNIN_CLEARDOWN = 'SIGNIN_CLEARDOWN';
