export const CHANGE_EMAIL_EMAIL_CHANGED = 'CHANGE_EMAIL_EMAIL_CHANGED';
export const CHANGE_EMAIL_SUCCESS = 'CHANGE_EMAIL_SUCCESS';
export const CHANGE_EMAIL_FAIL = 'CHANGE_EMAIL_FAIL';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
